package org.mega.entropycore

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The primary vector here isn't from memory or a hand-written cross-check
 * — it's a real-world example a beta tester posted, generated by
 * iancoleman.io/bip39 and independently confirmed with the `hal` CLI tool,
 * for mnemonic "super chest upgrade width same ten push repeat dove party
 * defy soon legal private coil art kick mule nature equip velvet moral
 * child burger" at m/44'/1'/0'/0/0 (BIP44, testnet). Reproducing a value
 * two independent external tools already agreed on is about as strong a
 * correctness signal as this project can get without a live device.
 */
class WifTest {

    @Test
    fun `matches a real-world tester-supplied vector from iancoleman-io and hal`() {
        val mnemonic = ("super chest upgrade width same ten push repeat dove party defy soon legal " +
            "private coil art kick mule nature equip velvet moral child burger").split(" ")

        val result = deriveWalletReceivePrivateKey(mnemonic, "", WalletScriptType.LEGACY, WalletNetwork.TESTNET, 0)

        assertEquals("m/44'/1'/0'/0/0", result.derivationPath)
        assertEquals("cR3T4ekPyDzqkWrCujwhWwJuUbYxrQS1oYhfHZkH6fwjJUrG96rB", result.wif)
    }

    @Test
    fun `mainnet WIF for the standard test mnemonic`() {
        val mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about".split(" ")
        val result = deriveWalletReceivePrivateKey(mnemonic, "", WalletScriptType.NATIVE_SEGWIT, WalletNetwork.MAINNET, 0)
        assertEquals("KyZpNDKnfs94vbrwhJneDi77V6jF64PWPF8x5cdJb8ifgg2DUc9d", result.wif)
    }

    @Test
    fun `a passphrase changes the WIF`() {
        val mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about".split(" ")
        val result = deriveWalletReceivePrivateKey(
            mnemonic,
            "correct horse battery staple",
            WalletScriptType.NATIVE_SEGWIT,
            WalletNetwork.TESTNET,
            0,
        )
        assertEquals("cUjLuQuXVovVNQBT7BMLTov2J8ePUvRhsFLwk3vKkb8HTE6LmKWN", result.wif)
    }

    @Test
    fun `mainnet and testnet WIFs for the same key differ only by prefix`() {
        val mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about".split(" ")
        val mainnet = deriveWalletReceivePrivateKey(mnemonic, "", WalletScriptType.LEGACY, WalletNetwork.MAINNET, 0)
        val testnet = deriveWalletReceivePrivateKey(mnemonic, "", WalletScriptType.LEGACY, WalletNetwork.TESTNET, 0)
        // Mainnet compressed WIFs start with K or L; testnet with c.
        assertTrue(mainnet.wif.first() in listOf('K', 'L'))
        assertTrue(testnet.wif.first() == 'c')
    }

    @Test
    fun `the WIF-encoded private key produces the same address deriveWalletAccountKeys already shows`() {
        val mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about".split(" ")
        val accountKeys = deriveWalletAccountKeys(mnemonic, "", WalletScriptType.NATIVE_SEGWIT, WalletNetwork.MAINNET, 0)
        val privateKey = deriveWalletReceivePrivateKey(mnemonic, "", WalletScriptType.NATIVE_SEGWIT, WalletNetwork.MAINNET, 0)
        assertEquals("m/84'/0'/0'/0/0", privateKey.derivationPath)
        assertEquals("bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu", accountKeys.firstReceiveAddress)
    }

    @Test
    fun `descriptor format matches script type`() {
        val mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about".split(" ")
        val legacy = deriveWalletReceivePrivateKey(mnemonic, "", WalletScriptType.LEGACY, WalletNetwork.MAINNET, 0)
        val nested = deriveWalletReceivePrivateKey(mnemonic, "", WalletScriptType.NESTED_SEGWIT, WalletNetwork.MAINNET, 0)
        val native = deriveWalletReceivePrivateKey(mnemonic, "", WalletScriptType.NATIVE_SEGWIT, WalletNetwork.MAINNET, 0)

        assertTrue(legacy.descriptor.startsWith("pkh([73c5da0a/44'/0'/0']xpub"))
        assertTrue(legacy.descriptor.endsWith("/0/0)"))
        assertTrue(nested.descriptor.startsWith("sh(wpkh([73c5da0a/49'/0'/0']ypub"))
        assertTrue(nested.descriptor.endsWith("/0/0))"))
        assertTrue(native.descriptor.startsWith("wpkh([73c5da0a/84'/0'/0']zpub"))
        assertTrue(native.descriptor.endsWith("/0/0)"))
    }

    @Test(expected = IllegalArgumentException::class)
    fun `rejects a negative account index`() {
        val mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about".split(" ")
        deriveWalletReceivePrivateKey(mnemonic, "", WalletScriptType.LEGACY, WalletNetwork.MAINNET, -1)
    }
}
