package org.mega.entropy.storage

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
private const val GCM_IV_LENGTH_BYTES = 12
private const val GCM_TAG_LENGTH_BITS = 128

fun aliasForSession(sessionId: String): String = "mega_session_$sessionId"

/**
 * Loads an existing AES-256 key from the Android Keystore for the given alias,
 * or generates a new one if it does not exist.
 *
 * WHY: We generate a dedicated key per session so that deleting a session
 * can also destroy its cryptographic key, ensuring forward secrecy for
 * that session's data. The key never leaves the secure hardware/keystore;
 * the app only ever gets a handle/reference to use it via Cipher, never
 * the raw key bytes.
 */
fun getOrCreateSecretKey(alias: String): SecretKey {
    val ks = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
    ks.getKey(alias, null)?.let { key ->
        if (key is SecretKey) return key
    }

    val spec = KeyGenParameterSpec.Builder(alias, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
        .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
        .setKeySize(256)
        .build()

    return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER)
        .apply { init(spec) }
        .generateKey()
}

/**
 * Encrypts plaintext using AES-256-GCM with a fresh IV generated by the Keystore.
 *
 * WHY: GCM requires a unique IV per encryption operation with the same key to
 * prevent nonce-reuse attacks that compromise confidentiality and authenticity.
 * We let the Cipher/Keystore generate it and prefix it to the ciphertext so
 * decryption can extract it later. The IV is not secret but must never repeat.
 */
fun encrypt(alias: String, plaintext: ByteArray): ByteArray {
    val key = getOrCreateSecretKey(alias)
    val cipher = Cipher.getInstance("AES/GCM/NoPadding")
    cipher.init(Cipher.ENCRYPT_MODE, key)
    val iv = cipher.iv
    val ciphertext = cipher.doFinal(plaintext)
    // Prepend IV (12 bytes) to ciphertext+tag
    return ByteArray(iv.size + ciphertext.size).apply {
        System.arraycopy(iv, 0, this, 0, iv.size)
        System.arraycopy(ciphertext, 0, this, iv.size, ciphertext.size)
    }
}

/**
 * Decrypts ciphertext that was prefixed with a 12-byte GCM IV.
 *
 * WHY: We explicitly load the existing key and throw if missing. Silently
 * creating a fresh key during decryption would just produce garbage instead
 * of failing loudly, masking data corruption or tampering.
 */
fun decrypt(alias: String, ivAndCiphertext: ByteArray): ByteArray {
    val ks = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
    val key = ks.getKey(alias, null) as? SecretKey
        ?: throw IllegalStateException("No Keystore key found for alias: $alias. Decryption cannot proceed safely.")

    if (ivAndCiphertext.size <= GCM_IV_LENGTH_BYTES) {
        throw IllegalArgumentException("Ciphertext too short to contain IV and data")
    }

    val iv = ivAndCiphertext.copyOfRange(0, GCM_IV_LENGTH_BYTES)
    val ciphertext = ivAndCiphertext.copyOfRange(GCM_IV_LENGTH_BYTES, ivAndCiphertext.size)

    val spec = GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv)
    val cipher = Cipher.getInstance("AES/GCM/NoPadding")
    cipher.init(Cipher.DECRYPT_MODE, key, spec)
    // Let AEADBadTagException propagate uncaught to fail closed on authentication failure
    return cipher.doFinal(ciphertext)
}

/**
 * Deletes the Keystore key for the given alias. Idempotent: no error if missing.
 */
fun deleteKey(alias: String) {
    val ks = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
    if (ks.containsAlias(alias)) {
        ks.deleteEntry(alias)
    }
}
